### ISSUE TITLE
How to change ssh port

### ISSUE THREAD

**Issue by arm-ARMY** [m5stack/M5Cardputer#2]
How do I connect to a non standard 22 port  with this script? Already connected to WiFi i've tried 

hostname:port

hostname port

And nothing seems to work.

Can help here? Thanks!

**Comment by Tinyu-Zhao** [comment]
Please do not ask questions in both repository.

**Comment by Tinyu-Zhao** [comment]
Refer to this issue https://github.com/ewpa/LibSSH-ESP32/issues/31
